import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles/globals.css'
import './styles/navbar.css'
import './styles/hero.css'
import './styles/services.css'
import './styles/projects.css'
import './styles/clients.css'
import './styles/cta.css'
import './styles/footer.css'
import './styles/pages.css'
import './styles/accents.css'
createRoot(document.getElementById('root')).render(<App />)
